---
- hosts: localhost
  vars:
    mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
    mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
    mssql_accept_microsoft_sql_server_standard_eula: true
    mssql_password: 'RedH@123!'
    mssql_edition: 'Developer'
    mssql_enable_sql_agent: false
    mssql_install_fts: false
    mssql_install_powershell: true
    mssql_tune_for_fua_storage: true

  roles:
    - microsoft.sql.server

- hosts: localhost
  tasks:
    - firewalld:
        service: mssql
        permanent: yes
        immediate: yes
        state: enabled

